/*
 * File: app/store/Fornitori.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GAS.store.Fornitori', {
    extend: 'Ext.data.Store',
    requires: [
        'GAS.model.Fornitore'
    ],
    config: {
        model: 'GAS.model.Fornitore',
        grouper: function (record) {
            return record.get('Titolo')[0];
        },
        storeId: 'Fornitori',
        autoLoad: true,
        autoSync: false,
        sorters: 'Titolo'
    }/*,
     data: [
     {"IDNegozio":"1","Titolo":"Frantoio D'Orazio","DescrizioneBreve":"Olio d'oliva dalla Puglia.","Descrizione":"","Image1":"20120523213007_.gif","Image1T":"20120512112954_1.jpg","Ordine":"1","DataIns":"2012-02-09 00:00:00","OperatoreIns":"Super user","IDTipoNegozio":"2","DataStato":"","OperatoreStato":"","IDStato":"1"},
     {"IDNegozio":"2","Titolo":"Bio Gourmet","DescrizioneBreve":"Bio Gourmet formaggi BIO.","Descrizione":"","Image1":"20120523212749_.jpg","Image1T":"","Ordine":"1","DataIns":"2012-02-11 00:00:00","OperatoreIns":" NUOVO UTENTE","IDTipoNegozio":"2","DataStato":"","OperatoreStato":"","IDStato":"2"},
     {"IDNegozio":"3","Titolo":"EOS","DescrizioneBreve":"Prodotti per l'igiene della persona.","Descrizione":"","Image1":"20120523212742_.png","Image1T":"20120329085353_.png","Ordine":"1","DataIns":"2012-03-29 00:00:00","OperatoreIns":"Super user","IDTipoNegozio":"2","DataStato":"","OperatoreStato":"","IDStato":"1"},
     {"IDNegozio":"4","Titolo":"Cooperativa Pace e Sviluppo","DescrizioneBreve":"Prodotti equosolidali.","Descrizione":"","Image1":"20120523212801_.jpg","Image1T":"","Ordine":"1","DataIns":"2012-05-23 00:00:00","OperatoreIns":"Super user","IDTipoNegozio":"2","DataStato":"","OperatoreStato":"","IDStato":"1"},
     {"IDNegozio":"5","Titolo":"Officina Naturae","DescrizioneBreve":"Prodotti naturali per l'igiene della casa e della persona.","Descrizione":"","Image1":"20120523213040_.gif","Image1T":"","Ordine":"1","DataIns":"2012-05-23 00:00:00","OperatoreIns":"Super user","IDTipoNegozio":"2","DataStato":"","OperatoreStato":"","IDStato":"2"},
     {"IDNegozio":"6","Titolo":"Blue Valley","DescrizioneBreve":"Prodotti ittici","Descrizione":"","Image1":"logo_blue_valley.png","Image1T":"","Ordine":"1","DataIns":"2012-10-09 00:00:00","OperatoreIns":"Super user","IDTipoNegozio":"2","DataStato":"","OperatoreStato":"","IDStato":"3"},
     {"IDNegozio":"7","Titolo":"Cosma","DescrizioneBreve":"Farine","Descrizione":"","Image1":"20121028133023_.png","Image1T":"","Ordine":"1","DataIns":"2012-10-28 00:00:00","OperatoreIns":"Super user","IDTipoNegozio":"2","DataStato":"","OperatoreStato":"","IDStato":"2"},
     {"IDNegozio":"8","Titolo":"Hierba Buena","DescrizioneBreve":"Fitopreparazione","Descrizione":"","Image1":"20121028133156_.gif","Image1T":"","Ordine":"1","DataIns":"2012-10-28 00:00:00","OperatoreIns":"Super user","IDTipoNegozio":"2","DataStato":"","OperatoreStato":"","IDStato":"2"},
     {"IDNegozio":"9","Titolo":"La Fattoria Veneta","DescrizioneBreve":"Prodotti bovini","Descrizione":"","Image1":"20121028133321_.gif","Image1T":"","Ordine":"1","DataIns":"2012-10-28 00:00:00","OperatoreIns":"Super user","IDTipoNegozio":"2","DataStato":"","OperatoreStato":"","IDStato":"2"},
     {"IDNegozio":"10","Titolo":"La Fagiana","DescrizioneBreve":"Riso","Descrizione":"","Image1":"20121028135624_.png","Image1T":"","Ordine":"1","DataIns":"2012-10-28 00:00:00","OperatoreIns":"Super user","IDTipoNegozio":"2","DataStato":"","OperatoreStato":"","IDStato":"2"},
     {"IDNegozio":"11","Titolo":"Le Barbarighe","DescrizioneBreve":"Macinazione a pietra cereali biologici di produzione propria","Descrizione":"","Image1":"20121028135827_.jpg","Image1T":"","Ordine":"1","DataIns":"2012-10-28 00:00:00","OperatoreIns":"Super user","IDTipoNegozio":"2","DataStato":"","OperatoreStato":"","IDStato":"2"},
     {"IDNegozio":"12","Titolo":"Iris","DescrizioneBreve":"Pasta","Descrizione":"","Image1":"20121028150330_.jpg","Image1T":"","Ordine":"1","DataIns":"2012-10-28 00:00:00","OperatoreIns":"Super user","IDTipoNegozio":"2","DataStato":"","OperatoreStato":"","IDStato":"1"},
     {"IDNegozio":"13","Titolo":"Alternativa","DescrizioneBreve":"Frutta e verdura","Descrizione":"","Image1":"20121028150518_.jpg","Image1T":"","Ordine":"1","DataIns":"2012-10-28 00:00:00","OperatoreIns":"Super user","IDTipoNegozio":"2","DataStato":"","OperatoreStato":"","IDStato":"2"},
     {"IDNegozio":"14","Titolo":"NEGOZIO TEST NON USARE","DescrizioneBreve":"NEGOZIO TEST NON USARE","Descrizione":"","Image1":"20121105190437_.jpg","Image1T":"","Ordine":"1","DataIns":"2012-11-05 00:00:00","OperatoreIns":"Super user","IDTipoNegozio":"2","DataStato":"","OperatoreStato":"","IDStato":"3"}
     ]*/
});