/*
 * File: app/view/MainMenu.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GAS.view.CarrelloList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.CarrelloList',
    requires: [
        'GAS.store.Carrello'
    ],
    config: {
        title: 'Carrello',
        grouped: true,
        indexBar: true,
        store: 'Carrello',
        loadingText: "Loading...",
        emptyText: '</pre><div class="carrello-vuoto">Carrello vuoto.</div><pre>',
        onItemDisclosure: true,
        //itemTpl: '<table><tr><td width="400">{Titolo}</td><td width="100" style="text-align:right">{Quantita}</td></tr></table>'
        itemTpl: '</pre><div class="list-item-fornitore">{Fornitore}</div><div class="list-item-prodotto"><table><tr><td width="400">{Titolo}</td><td width="100" style="text-align:right">{Quantita}</td></tr></table></div><pre>'
    }
});