/*
 * File: app/view/MainMenu.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */


Ext.define('GAS.view.Main', {
    extend: 'Ext.TabPanel',
    alias: "widget.main",

    config: {

        fullscreen: true,
        tabBarPosition: 'bottom',

        items: [
            // This is the home page, just some simple html
            // ActiveItem(0)
            {
                title: 'Home',
                iconCls: 'home',
                cls: 'home',
                html: [
                    '<div style="text-align:center"><img height=200 width=200 src="images/logoGas.jpg"/></div>',
                    '<h1 style="text-align:center">Gruppo Acquisto Solidale</h1>',
                    '<h1 style="text-align:center">Monastier di Treviso</h1>',
                    //"<p>Benvenuti in Gas Mobile!!</p>",
                    '<br>',
                    //'<h2 style="text-align:center">by <a href="http://www.mauromarson.eu" target="_blank">Mauro Marson</a></h2>'
                ].join("")
            },

            // ActiveItem(1)
            {
                xtype: 'Login',
                title: 'Ordini',
                iconCls: 'search',
                cls: 'search',
                //the badgetext configuration allows us to add a badge/tooltip onto the tab
                //this is useful when you want to notify users of new content in an unactive tab
                badgeText: null

            },
            // ActiveItem(2)
            {
                xtype: 'FornitoriNavigation'
            },
            // ActiveItem(3)
            {
                xtype: 'CategorieNavigation'
            },
            // ActiveItem(4)
            {
                xtype: 'ProdottiNavigation'
            },
            // ActiveItem(5)
            {
                xtype: 'ProdottiDetail'
            },
            // ActiveItem(6)
            {
                xtype: 'UserSetting'
            },
            // ActiveItem(7)
            {
                xtype: 'CarrelloNavigation'
            },
            // ActiveItem(8)
            {
                xtype: 'CarrelloDetail'
            },
            // This is the recent blogs page. It uses a tree store to load its data from blog.json
            {
                xtype: 'Blog',
                title: 'Blog',
                iconCls: 'star',
                cls: 'blog'
            },

            // This is the contact page, which features a form and a button. The button submits the form
            {
                xtype: 'Contact',
                title: 'Contact Us',
                iconCls: 'compose'

            },

            // Info Page
            {
                title: 'Info',
                iconCls: 'info',
                cls: 'info',
                html: [
                    //'<img height=260 src="http://staging.sencha.com/img/sencha.png" />',
                    '<h1>Versione 1.0</h1>'
                    //"<p>Building the Getting Started app</p>",
                    //'<h2>Sencha Touch 2</h2>'
                ].join("")
            }
        ]
    }
    /*,
     initialize: function () {
     console.log('initialize function di Main');
     }*/
});