/*
 * File: app/view/Login.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

var Fornitori = {
    style: "background-color: #FFBF00; color: white;",
    title: 'Fornitori',
    html: 'Fornitori',
    action: 'fornitori'
};

var Articoli = {
    style: "background-color: #000000; color: white;",
    title: 'Articoli',
    html: 'Articoli',
    action: 'articoli'
};

var Carrello = {
    style: "background-color: #00FF00; color: white;",
    title: 'Carrello',
    html: 'Carrello',
    action: 'carrello'
};

Ext.define('GAS.view.Options_ok', {
    extend: 'Ext.Container',
    alias: "widget.Options",

    config: {
        fullscreen: true,
        layout: {
            type: 'vbox',
            pack: 'center'
        },
        defaults: {
            flex: 1
        },
        navigationBar: {
            //ui: 'light',
            docked: 'top',
            height: 40,
            items: [
                {
                    xtype: 'button',
                    text: 'Log Off'
                }
            ]
        },
        items: [
            {
                docked: 'top',
                xtype: 'titlebar',
                title: 'Menù',
                items: [
                    {
                        xtype: 'button',
                        action: 'logoff',
                        text: 'Log Off'
                    }
                ]
            },
            /*
             {
             xtype: 'button',
             action: 'fornitori',
             text: 'fornitori'
             //height:30

             },
             {
             xtype: 'button',
             action: 'articoli',
             text: 'articoli'
             //height:30

             },
             {
             xtype: 'button',
             action: 'carrello',
             text: 'carrello'
             //height:30

             },
             */
            Fornitori,
            Articoli,
            Carrello
        ]
    }

});