/*
 * File: app/view/Login.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GAS.view.Ordini', {
    extend: 'Ext.Panel',
    alias: "widget.Ordini",

    config: {

        layout: 'card',
        //useTitleForBackButtonText: false,
        //fullscreen: true,
        title: 'Ordini',
        items: [
            {
                xtype: 'Login'
            }
            ,
            {
                xtype: 'Options'
            }

        ]
    },
    init: function () {
        console.log('init function di Ordini');
    }
    /*,
     initialize: function () {
     console.log('initialize function di Ordini');

     }
     */
});