/*
 * File: app/view/MainMenu.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GAS.view.ProdottiList', {
    extend: 'Ext.List',
    alias: 'widget.ProdottiList',
    requires: [
        'GAS.store.Prodotti'
    ],
    config: {
        title: 'Prodotti',
        grouped: true,
        indexBar: true,
        store: 'Prodotti',
        loadingText: "Loading...",
        onItemDisclosure: true,
        itemTpl: '<table><tr><td><img src="http://www.gasmonastier.it/gasstore/allegati/{Image1}" height="50" width="100" /></td><td width="300" style="text-align:left">{Titolo}</td><td width="100" style="text-align:right">Prezzo</td><td width="100" style="text-align:right">{Prezzo}</td><td>&#128;</td></tr></table>'
    }
});