/*
 * File: app/view/MainMenu.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GAS.view.ProdottiList', {
    extend: 'Ext.List',
    alias: 'widget.ProdottiList',
    requires: [
        'GAS.store.Prodotti'
    ],
    config: {
        title: 'Prodotti',
        grouped: true,
        indexBar: true,
        store: 'Prodotti',
        loadingText: "Loading...",
        onItemDisclosure: true,
        itemTpl: '' +
            '<table>' +
            '<tr>' +
            '<td width="100">' +
            '<img src="http://www.gasmonastier.it/gasstore/allegati/{Image1}" height="50" width="50" />' +
            '</td>' +
            '<td width="300" style="text-align:left">{Titolo}</td>' +
            '<td width="60" style="text-align:right">Prezzo</td>' +
            '<td width="60" style="text-align:right">{Prezzo}</td>' +
            '<td>&#128;</td>' +
            '<td width="100" style="text-align:right">Nr acquisti</td>' +
            '<td width="100" style="text-align:right">{NrAcquisti}</td>' +
            //'<td width="150" style="text-align:right">Like</td>' +
            '<td width="100">' +
            '<img src="images/facebook_like.jpg" height="30" width="30" />' +
            '</td>' +
            '<td width="40" style="text-align:right">{Like}</td>' +
            //'<td width="150" style="text-align:right">Dislike</td>' +
            '<td width="100">' +
            '<img src="images/facebook_dislike.jpg" height="30" width="30" />' +
            '</td>' +
            '<td width="40" style="text-align:right">{Dislike}</td>' +
            '<td width="100" height="50">' +
            '<div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-width="100" data-height="50" data-layout="button" data-action="like" data-show-faces="false" data-share="true"></div>' +
            '</td>' +
            '</tr>' +
            '</table>'
    }
});