/*
 * File: app/model/Articoli.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GAS.model.Carrello', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            //{ name: 'IDDettagliOrdine', type: 'int' },    // autoincrement
            { name: 'Codice', type: 'string' },             // codice prodotto
            { name: 'Titolo', type: 'string' },             // titolo prodotto
            { name: 'DescrizioneBreve', type: 'string' },   // descrizione
            { name: 'Prezzo', type: 'double' },             // prezzo
            { name: 'DataIns', type: 'date', dateFormat: 'Y-m-d H:i:s'},  // data inserimento
            { name: 'OperatoreIns', type: 'string' },       // UserName
            { name: 'IDProdotto', type: 'int' },            // id prodotto
            { name: 'Quantity', type: 'int' },              // quantità
            { name: 'IDOrdine', type: 'int' },              // null
            { name: 'Fornitore', type: 'string' },          // fornitore
            { name: 'Importo', type: 'double' },            // importo
            { name: 'IDUtente', type: 'int' },              // IDUtente
            { name: 'IDFornitore', type: 'int' }            // IDFornitore
        ],
        proxy: {
            type: 'ajax',
            actionMethods: 'POST',

            api: {
                read: ' TODO/read',
                create: 'setTable.php',
                destroy: 'TODO/Delete',
                update: 'TODO/Update'
            },
            reader: {
                type: 'json',
                rootProperty: 'data',
                idProperty: 'IDProdotto',
                successProperty: 'success',
                messageProperty: 'message'
            },
            writer: {
                type: 'json',
                root: 'data',
                encode: true,
                writeAllFields: true,
                successProperty: 'success',
                messageProperty: 'message'
            },
            listeners: {
                exception: function () {
                    console.log("Exception on Carrello");
                }
            }
        }
    },
    fullName: function () {
        var d = this.data,
            names = [
                d.Titolo
            ];
        return names.join(" ");
    }
});