/*
 * File: app/model/Fornitori.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GAS.model.Fornitore', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            { name: 'IDNegozio', type: 'string' },
            { name: 'Titolo', type: 'string' },
            { name: 'DescrizioneBreve', type: 'string' },
            { name: 'Descrizione', type: 'string' },
            { name: 'Image1', type: 'string' },
            { name: 'Image1T', type: 'string' },
            { name: 'Ordine', type: 'string' },
            { name: 'DataIns', type: 'date' },
            { name: 'OperatoreIns', type: 'string' },
            { name: 'Super user', type: 'string' },
            { name: 'IDTipoNegozio', type: 'string' },
            { name: 'DataStato', type: 'date' },
            { name: 'OperatoreStato', type: 'string' },
            { name: 'IDStato', type: 'string' }
        ],
        proxy: {
            type: 'ajax',
            actionMethods: 'POST',
            extraParams: {
                tableName: 'Negozi'
            },
            api: {
                read: ' getTable.php',
                create: 'TODO/Create',
                destroy: 'TODO/Delete',
                update: 'TODO/Update'
            },
            reader: {
                type: 'json',
                rootProperty: 'data',
                idProperty: 'IDNegozio',
                successProperty: 'success',
                messageProperty: 'message'
            },
            writer: {
                type: 'json',
                root: 'data',
                encode: true,
                writeAllFields: true
            },
            listeners: {
                exception: function () {
                    console.log("Exception on Fornitori");
                }
            }
        }
    },
    fullName: function () {
        var d = this.data,
            names = [
                d.Titolo,
                (!d.DescrizioneBreve ? "" : d.DescrizioneBreve + "."),
                d.Descrizione
            ];
        return names.join(" ");
    }
});