/*
 * File: app/model/Articoli.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GAS.model.ProdottoLike', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            { name: 'id', type: 'int' },
            { name: 'idNegozio', type: 'int' },
            { name: 'idUtente', type: 'int' },
            { name: 'CodiceProdotto', type: 'string' },
            { name: 'Like', type: 'int' },
            { name: 'Dislike', type: 'int' },
            { name: 'Commenti', type: 'string' },
            { name: 'DataInserimento', type: 'date' }
        ],
        proxy: {
            type: 'ajax',
            actionMethods: 'POST',
            extraParams: {
                tableName: 'ProdottiLike',
                select: '*',
                orderBy: 'CodiceProdotto',
                where: ''
            },
            api: {
                read: ' getTable.php',
                create: 'TODO/Create',
                destroy: 'TODO/Delete',
                update: 'TODO/Update'
            },
            reader: {
                type: 'json',
                rootProperty: 'data',
                idProperty: 'id',
                successProperty: 'success',
                messageProperty: 'message'
            },
            writer: {
                type: 'json',
                root: 'data',
                encode: true,
                writeAllFields: true
            },
            listeners: {
                exception: function () {
                    console.log("Exception on ProdottiLike");
                }
            }
        }
    },
    fullName: function () {
        var d = this.data,
            names = [
                d.CodiceProdotto
            ];
        return names.join(" ");
    }
});