/*
 * File: app/model/Fornitori.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GAS.model.Utente', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            { name: 'Nome', type: 'string' },
            { name: 'Cognome', type: 'string' },
            { name: 'UserName', type: 'string' },
            { name: 'PWD', type: 'string' },
            { name: 'Telefono', type: 'string' },
            { name: 'FAX', type: 'string' },
            { name: 'Email', type: 'string' },
            { name: 'Indirizzo', type: 'string' },
            { name: 'CAP', type: 'string' },
            { name: 'Citta', type: 'string' },
            { name: 'Provincia', type: 'string' },
            { name: 'DataIns', type: 'date' },
            { name: 'OperatoreIns', type: 'string' },
            { name: 'IDTipoUtente', type: 'int' },
            { name: 'DataStato', type: 'date' },
            { name: 'OperatoreStato', type: 'string' },
            { name: 'IDStato', type: 'int' }

        ],
        proxy: {
            type: 'ajax',
            actionMethods: 'POST',
            extraParams: {
                tableName: 'Utenti'
            },
            api: {
                read: ' getTable.php',
                create: 'TODO/Create',
                destroy: 'TODO/Delete',
                update: 'TODO/Update'
            },
            reader: {
                type: 'json',
                rootProperty: 'data',
                idProperty: 'UserName',
                successProperty: 'success',
                messageProperty: 'message'
            },
            writer: {
                type: 'json',
                root: 'data',
                encode: true,
                writeAllFields: true
            },
            listeners: {
                exception: function () {
                    console.log("Exception on Utenti");
                }
            }
        }
    },
    fullName: function () {
        var d = this.data,
            names = [
                d.UserName,
                (!d.Nome ? "" : d.Nome + "."),
                d.Cognome
            ];
        return names.join(" ");
    }
});